#!/bin/bash


DD1=`date -d "1 day ago" | awk -F " " '{print $2,$3}'`
DD2=`date -d "1 day ago" +%Y-%m-%d`

BASE_DIR=" /JenkinsData/jobs"
DEST_DIR="/gms2/Hudson_cfgbak/master_10.0.1.99"


## Find All Today's Node
for job in `ls  /JenkinsData/jobs`
do
/bin/mkdir -p $DEST_DIR/$job

/bin/ls -l  /JenkinsData/jobs/$job/builds |  grep "$DD2" | grep -v ">" | awk -F " " '{print $9}'  >>  $DEST_DIR/$job/Node.txt
## Copy Files
for  node in $(cat $DEST_DIR/$job/Node.txt)
do

mkdir -p $DEST_DIR/$job/$node

find $BASE_DIR/$job/builds/$node/ -name modification.tx -exec cp  $DEST_DIR/$job/$node/
find $BASE_DIR/$job/builds/$node/ -name pre_manifest.xml -exec cp  $DEST_DIR/$job/$node/
find $BASE_DIR/$job/builds/$node/ -name changelog.build.txt -exec cp  $DEST_DIR/$job/$node/
find $BASE_DIR/$job/builds/$node/ -name changelog.day.txt -exec cp  $DEST_DIR/$job/$node/
find $BASE_DIR/$job/builds/$node/ -name changelog.2week.txt -exec cp  $DEST_DIR/$job/$node/
find $BASE_DIR/$job/builds/$node/ -name changelog.month.txt -exec cp  $DEST_DIR/$job/$node/
/bin/cp $BASE_DIR/$job/builds/$node/build.xml   $DEST_DIR/$job/$node/
/bin/cp $BASE_DIR/$job/builds/$node/changelog.xml       $DEST_DIR/$job/$node/
/bin/cp $BASE_DIR/$job/builds/$node/archive/BT_Version.txt  $DEST_DIR/$job/$node/
/bin/cp $BASE_DIR/$job/builds/$node/archive/*.xml  $DEST_DIR/$job/$node/
/bin/cp $BASE_DIR/$job/builds/$node/archive/IDH/manifest.xml  $DEST_DIR/$job/$node/
/bin/cp $BASE_DIR/$job/builds/$node/archive/*.txt  $DEST_DIR/$job/$node

done
done
